WeatherForecast/Models/Dto/OpenWeatherAPIDTO.cs
namespace WeatherForecast.Models.Dto
{
    public class OpenWeatherAPIDTO
    {
        public string? name { get; set; }
        public TemperatureInfoDTO? main { get; set; }
        public List<WeatherInfoDTO>? weather { get; set; }
        public WindInfoDTO? wind { get; set; }
        public string? WarningMessage { get; set; }
    }
}

WeatherForecast/Models/Dto/TemperatureInfoDTO.cs
namespace WeatherForecast.Models.Dto
{
    public class TemperatureInfoDTO
    {
        public double temp { get; set; }
        public double temp_min { get; set; }
        public double temp_max { get; set; }
    }
}

WeatherForecast/Models/Dto/WeatherInfoDTO.cs
namespace WeatherForecast.Models.Dto
{
    public class WeatherInfoDTO
    {
        public string main { get; set; }
    }
}

WeatherForecast/Models/Dto/WindInfoDTO.cs
namespace WeatherForecast.Models.Dto
{
    public class WindInfoDTO
    {
        public double speed { get; set; }
    }
}

WeatherForecast/Models/View/WeatherForecastVM.cs
using System.ComponentModel.DataAnnotations;

namespace WeatherForecast.Models.View
{
    public class WeatherForecastVM
    {
        [Required(ErrorMessage = "You must enter the name of the city so we can send you the information!")]
        [RegularExpression("^[a-zA-ZšđčćžŠĐČĆŽ ]+$", ErrorMessage = "You did not enter the name correctly!")]
        public string City { get; set; }
    }
}

WeatherForecast/Controllers/WeatherForecastController.cs
using Microsoft.AspNetCore.Mvc;
using WeatherForecast.Models.Dto;
using WeatherForecast.Models.View;
using WeatherForecast.Service.IService;

namespace WeatherForecast.Controllers
{
    public class WeatherForecastController : Controller
    {
        private readonly IWeatherForecastService _weatherService;

        public WeatherForecastController(IWeatherForecastService weatherService)
        {
            _weatherService = weatherService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult WeatherForecastPage()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult WeatherForecastPage(WeatherForecastVM model)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(ShowForecastPage), new { city = model.City });
            }
            else
            {
                return View();
            }
        }

        public async Task<IActionResult> ShowForecastPage(string city)
        {
            var response = await _weatherService.GetWeatherInfo(city);
            if (response != null)
            {
                var model = new OpenWeatherAPIDTO
                {
                    name = response.name,
                    main = response.main,
                    weather = response.weather,
                    wind = response.wind
                };
                return View(model);
            }
            else
            {
                return View();
            }
        }
    }
}

WeatherForecast/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeatherForecast.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Playwrite+AU+SA:wght@100..400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="icon" type="image/svg" href="/images/browser-image.svg" />
</head>
<body>
    <header>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WeatherForecast
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WeatherForecast/Views/WeatherForecast/Index.cshtml
@{
    ViewData["Title"] = "Welcome - Weather Forecast";
}
<div class="container text-center">
    <div class="glavniDeo">
    <h1><strong>Welcome to Weather Forecast!!!</strong></h1><br />
    <h4>Explore the weather forecast info for most cities around the world!</h4><br />
    <a asp-action="WeatherForecastPage" asp-controller="WeatherForecast" class="btn">Go to Weather Forecast</a>
    </div>
</div>

WeatherForecast/Views/WeatherForecast/ShowForecastPage.cshtml
@using WeatherForecast.Models.Dto
@model OpenWeatherAPIDTO
@{
    ViewData["Title"] = $"{Model.name} - WeatherForecast";
}

<div class="container text-start">
    
    @if (Model.name != null && Model.weather != null && Model.main != null && Model.wind != null && Model.WarningMessage == null)
    {
        <br />
        <p><i class="bi bi-building"></i> <b>City:</b> @Model.name</p>
        <br />
        @foreach (var weather in Model.weather)
        {
            <p><i class="bi bi-cloud-sun"></i> <b>Weather description:</b> @weather.main</p>
        }
        <br />
        <p><i class="bi bi-thermometer-half"></i> <b>Temperature:</b> @(Math.Round((Model.main.temp - 32) * 5.0 / 9.0, 1)) °C</p>
        <br />
        <p><i class="bi bi-thermometer-low"></i> <b>Minimum temperature:</b> @(Math.Round((Model.main.temp_min - 32) * 5.0 / 9.0, 1)) °C</p>
        <p><i class="bi bi-thermometer-high"></i> <b>Maximum temperature:</b> @(Math.Round((Model.main.temp_max - 32) * 5.0 / 9.0, 1)) °C</p>
        <br />
        <p><i class="bi bi-wind"></i> <b>Wind speed:</b> @Model.wind.speed m/s</p>
    } else if (Model.WarningMessage != null){
        <p><b>@Model.WarningMessage</b></p>
    }
    else {
        <p><b>Unfortunately, we are currently unable to provide data for the requested location.</b></p>
    }
    <br />
    <div class="text-center">
    <a asp-action="WeatherForecastPage" asp-controller="WeatherForecast" class="btn w-50">Back to Weather Forecast</a>
    </div>
</div>

WeatherForecast/Views/WeatherForecast/WeatherForecastPage.cshtml
@using WeatherForecast.Models.View
@model WeatherForecastVM
@{
    ViewData["Title"] = "WeatherForecast";
}

<div class="container text-center">
    <h1 class="naslovi">Enter the name of the city</h1>
    <form asp-action="WeatherForecastPage">
        <br />
        <input asp-for="City" class="form-control w-50 mx-auto"/><br />
        <span asp-validation-for="City" class="errorPoruke"></span>
        <br /><br />
        <input type="submit" class="btn" />
    </form>
</div>